theme = "nord"

[editor]
# システムクリップボードを使用
clipboard-provider = "pasteboard"
default-yank-register = "+"

[editor.soft-wrap]
enable = true

[editor.cursor-shape]
normal = "block"
insert = "bar"       # Vim風: insertモードで縦線
select = "underline"

[keys.insert.j]
k = "normal_mode"    # jk でnormalモードへ（Vim風）
